### ISSUE TITLE
[Spike] Dask Scheduling

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#115]
# Purpose
Determine design for a full Dask execution of the identity graph.

Pieces to consider:
- Does dask support queuing jobs, or should we use something like celery for this
- Can jobs be directed to multiple queues?
- instead of executing id graph within a separate thread, we should be able to use dask's worker abstraction?

# Background

As part of the async improvement works we uncovered an issue where the application database runs out of available connections when enough privacy requests are created at once (https://github.com/ethyca/fidesops/pull/106#pullrequestreview-825697435). Despite major optimisation work done pre-merging of https://github.com/ethyca/fidesops/pull/106, the problem still theoretically persists.

This ticket is to investigate potential solutions to this problem, such that Fidesops will never error out of processing a privacy request because of connection limitations with the application database. Should we be using a queue here?

It seems to me that a desirable architecture would sit the DB connections at container level, then delegate those connections to processes, instead of each process creating its own connection to the database as is currently happening. That way we can be implicitly sure that when work is happening on any of our nodes, there is a database connection available.

**Comment by iamkelllly** [comment]
Is a dependency to be completed before #111

**Comment by stevenbenjamin** [comment]
The application _should_ use a singleton pool to connect to the application database. Since the last set of changes that should _mostly_ be happening, This means that we should never have more connections than the ( size of the pool)  X  (number of running instances) with the current task runner setup.I'd like to figure out a way to test this. 

If/when the tasks move to distributed dask runners (or even to separate processes) this will get more complicated, as each runner will need its own thread pool to connect to the app database (to write to the execution logs, for example). More of an issue, I think, is that each runner will  potentially also need a connection to each database in the traversal graph.

We can mitigate this by moving to a sqlAlchemy `NullPool` for sql databases, which holds no connections. Possibly other connection types can be similarly configured.

**Comment by pattisdr** [comment]
https://github.com/ethyca/fidesops/pull/145 is a small PR that came out of early research for this, but more to do here -

**Comment by pattisdr** [comment]
Moving this back to "TODO". I have not worked on this this week -

**Comment by adriaaaa** [comment]
@pattisdr another use case that just came up for this Dask scheduling is for our DRP Implementation. As part of the DRP spec, we will need to support a privacy request status callback (see this https://github.com/ethyca/fidesops/issues/419 for more information). Giving you a heads up in case that alters/adds to any of the research you had originally planned.
