### ISSUE TITLE
[Admin UI] [Spike] Deployment

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#389]
### Is your feature request related to a specific problem?

The Admin UI currently comes with no deployment method beyond running it locally. Ideally we'd like to serve this directly from the Fidesops server for extra security. This means that it's possible to set the frontend so it's only accessible from within a certain network.

### Describe the solution you'd like

- [ ] Serve the admin UI directly from Fidesops at some URL (e.g. `/admin`)
- [ ] Add this to the README
- [ ] Add this to the documentation

**Comment by allisonking** [comment]
The approach we're taking on the fidesctl side is:

* Configure the server to host static files (https://github.com/ethyca/fides/pull/621). We're hosting it right at the root (i.e. localhost:8080, but should also be simple to configure it to be at `/admin`)
* Add some commands to the Dockerfile so that it'll build the frontend and copy it to the right place (scaffolded out also in https://github.com/ethyca/fides/pull/621, but since there isn't a real frontend yet, isn't a real build yet)
* Add a line to the package.json to easily copy the build directory over to where the python server expects it (todo)
