### ISSUE TITLE
Query execution for Redshift

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fidesops#74]
Requires #45 to be complete first.

We need to enable the Redshift database connector to be able to read/write to the database itself during query execution.

**Comment by pattisdr** [comment]
In  https://github.com/ethyca/fidesops/pull/56 I added the `sqlalchemy-redshift` requirement, since [Amazon Redshift now has native support for SQLAlchemy](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-redshift-sqlalchemy-apache-airflow-open-source-frameworks/).  Redshift is based on postgres so hopefully our existing SQL connector will get us a lot of the way there, although there may be things we need to work out related to the [differences between redshift and postgres](https://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html).
