### ISSUE TITLE
`ConnectionConfig` for Microsoft SqlServer

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fidesops#78]
Fidesops must support connecting to a SqlServer instance. Test connection details can be found by contacting @iamkelllly 

This issue represents just the connection, query building for SqlServer will come in a subsequent issue.

**Comment by pattisdr** [comment]
foundation started on branch [fidesops_78_microsoft_sql_server](https://github.com/ethyca/fidesops/tree/fidesops_78_microsoft_sql_server). Ran into issues with MSSQL not yet being supported on M1 architecture, but there are suggestions to use an Azure SQL Edge image instead, although the differences between these may matter.  There are also some questions about which SQLAlchemy dialect/DBAPI to use, ran into early issues with PyODBC and pymssql. Plan for now is I'm going to pick up something else and a non-m1 chip user will take over.

**Comment by pattisdr** [comment]
foundation started on branch [fidesops_78_microsoft_sql_server](https://github.com/ethyca/fidesops/tree/fidesops_78_microsoft_sql_server). Ran into issues with [MSSQL not yet being supported on M1 architecture](https://github.com/microsoft/mssql-docker/issues/668), but there are suggestions to use an Azure SQL Edge image instead, although the differences between these may matter.

There are also some questions about which SQLAlchemy dialect/DBAPI to use, ran into early M1 issues with [PyODBC](https://stackoverflow.com/questions/66896068/pyodbc-on-m1-macs) and pymssql (issues building wheels, but maybe not worth pursuing because sqlalchemy docs say it is unmaintained).

Plan is that I'm just going to stop investigation and a non-m1 chip user will take over.
